---
- name: create systemd.unit file for nexus
  ansible.builtin.template: 
    src: "templates/nexus.service.j2"
    dest: "/etc/systemd/system/nexus.service"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_user }}"
    mode: 0644